title: Jorge Munoz
logo: 
description: >
  Jorge is an accomplished Data Analyst specializing in Power BI and SharePoint development, currently working in the government contracting sector. 
  He brings a proven track record in end-to-end data analysis, knowledge and data management, and digital transformation, making him a reliable go-to professional in this field.

  Notably, his automated training management and analytics solution earned widespread recognition through a disseminated white paper, contributing to numerous successful proposals.
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/jorge-munoz-2a09371b6/">View My LinkedIn Profile
theme: jekyll-theme-minimal
