title: Jorge Munoz
logo: 
description: >
  Jorge Munoz is an accomplished Data Analyst specializing in Power BI analytic solutions and SharePoint site development for the government contracting sector. 
  With a proven track record in dashboard developmment, data modeling
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/jorge-munoz-2a09371b6/">View My LinkedIn Profile
theme: jekyll-theme-minimal
