title: Jorge Munoz
logo: 
description: >
  Hello! Welcome to my personal website. This is a collection of projects, past and present, that aim to highlight some of my areas of technical expertise. Keep reading to learn a little more about me.  
  <br><br>
  I am a Data Analyst specializing in Power BI and SharePoint development, currently working in the government contracting sector. I bring a 
  proven track record in end-to-end data analysis, knowledge management, and digital transformation, making me a reliable go-to professional in this field.
  <br><br>
  I have an academic background in Computer Science & Physics from Texas A&M University, an Analytics certificate from The Georgia Institute of Technology, and I plan to begin my graduate studies 
  in Artificial Intelligence at the University of Texas at Austin in 2024.
  <br><br>
  As a lifelong learner, I am passionate about democratizing knowledge access. My current research interests lie at the intersection of NLP and Graph Networks. I envision the unification of Large Language Models (LLMs) and 
  Knowledge Graphs as having the potential to revolutionize information retrieval and understanding. Through a seamless integration of structured and 
  unstructured data, we could achieve faster decision-making, enhanced natural language interactions, and deeper insights across diverse domains. 
  <br><br>
  <a href="https://www.linkedin.com/in/jorge-munoz-2a09371b6/">View My LinkedIn Profile
theme: jekyll-theme-minimal
