title: Jorge Munoz
logo: 
description: >
  First description
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/jorge-munoz-2a09371b6/">View My LinkedIn Profile
theme: jekyll-theme-minimal
